- hosts: aws
  become: true

  vars:
    udacity: true
    ansible: false

  tasks:
    - name: Create 2 groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - "udacity_group"
        - "ansible_group"

    - name: Create Udacity folder
      file:
        path: /tmp/udacity
        state: directory
      when: udacity

    - name: Create ansible folder
      file:
        path: /tmp/ansible
        state: directory
      when: not ansible

    - name: Debug aws group_var
      debug:
        msg: "{{ aws_group_var }}"


