- hosts: aws
  become: true

vars:
  app_root: "www.audacity.com"
  http_port: "80"

tasks:
  - name: Create nginx config directory
    file: 
      path: /etc/nginx
      state: directory

  - name: Copy nginx configuration
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf

